import { type NextPage } from "next";
import Head from "next/head";
import ChatWindow from "./ChatWindow";



const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full flex-col items-center justify-center bg-slate-50">
      <ChatWindow/>
    </main>
    </>
  );
};

export default Home;
