import { type NextPage } from "next";
import Head from "next/head";
import ChatWindow from "./ChatWindow";


function classNames(...classes: string[]) {
  return classes.filter(Boolean).join(' ')
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
      <ChatWindow/>
    </main>
    </>
  );
};

export default Home;
